#!/bin/bash
# Not meant to be portable: mostly for documentation purposes.
# Stores build artiacts one directory above the root repository directory.
# Builds to ../build
# Installs to ../install

set -eou pipefail

set -x

REPO_DIR="$(readlink -f $(dirname $0))"

(
    cd ../
    mkdir -p install
    cmake \
        -G "Unix Makefiles" \
        -B build \
        -S "${REPO_DIR}" \
        -DCMAKE_INSTALL_PREFIX=./install

    cmake --build build \
        --parallel $(nproc) \
        --target install
)
